name: CI

on: 
  push:
    branches: 
      - master
      - release/*
  
  pull_request:

  release:
      types: [published, created, edited]
jobs:
  build:
    name: hello world
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    
