name: Send Weather Mail

on: [push]
  
jobs:
  build:
    name: My Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: 'Install NPM dependencies'
      run: npm install nodemailer 
        
    - name: Run
      run: node index.js
    
    
